---
title: "data_meta"
author: "Coulibaly Zie Mamadou"
date: "2023-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#webshot::install_phantomjs()
options(knitr.table.format = "html")
library(kableExtra)
library(robvis)
library(knitr)
library(webshot)
library(robvis)
library(metafor)
library(meta)
library(tidyverse)

```



```{r}
data <- read.csv("data_final_suite.csv",sep=";",fileEncoding = "Latin1", check.names = F)
```


```{r}
data
```


```{r}
view(data)
```

```{r}
names(data)
```
```{r}
is.na(data)
```


```{r}

dat <- escalc(measure="RR", ai=MgHIVpositif, bi=MgHIVnegatif, ci=ControleHIVpositif, di=ControleHIVnegatif, data=data,
              slab=paste(Auteurs, Année, sep=", ")) # also add study labels
dat

```


```{r}
# fit random-effects model
res <- rma(yi, vi, data=dat, test="knha")
res


```

```{r}
# predicted pooled risk ratio (with 95% confidence/prediction intervals)
predict(res, transf=exp, digits=2)


```
names(data)
```{r}
names(data)

```
```{r}
### get the weights and format them as will be used in the forest plot
weights <- formatC(weights(res), format="f", digits=1)
```



```{r}
### get the weights and format them as will be used in the forest plot
weights <- formatC(weights(res), format="f", digits=1)
 
### adjust the margins
par(mar=c(2.7,3.2,2.3,1.3), mgp=c(3,0,0), tcl=0.15)


```

```{r}
# forest plot
sav<-forest(res, atransf=exp, at=log(c(.05, .25, 1, 4)), xlim=c(-16,6),
       showweights=TRUE,addfit=TRUE, addpred=TRUE,annotate=TRUE,
       ilab=cbind(MgHIVpositif, MgHIVnegatif, ControleHIVpositif, ControleHIVnegatif), ilab.xpos=c(-9.5,-8,-6,-4.5), shade="zebra",
       header="Author(s) and Year")
text(c(-9.5,-8,-6,-4.5), res$k+2, c("HIV+", "HIV-", "HIV+", "HIV-"), font=2)
text(c(-8.75,-5.25),     res$k+3, c("MgSO4", "Control"), font=2)

res <- rma(yi, vi, data=dat, test="knha")
res

### add the 100.0 for the sum of the weights
text(sav$ilab.xpos[3], 0, "100.0")
 
### add the column totals for the counts and sample sizes
text(sav$ilab.xpos[1:2], 0, c(paste(sum(dat$ai), "/", sum(dat$n1i)), paste(sum(dat$ci), "/", sum(dat$n2i))))
 
### add text with heterogeneity statistics
text(sav$xlim[1], -1, pos=1, bquote(paste("Test for heterogeneity: ", tau^2, "=",
     .(formatC(res$tau2, digits=2, format="f")), "; ", chi^2, "=",
     .(formatC(res$QE, digits=2, format="f")), ", df=", .(res$k - res$p),
     ", P=", .(formatC(res$QEp, digits=2, format="f")), "; ", I^2, "=",
     .(formatC(res$I2, digits=0, format="f")), "%")))
 
### add text for test of overall effect
text(sav$xlim[1], -2, pos=1, bquote(paste("Test for overall effect: Z=",
     .(formatC(res$zval, digits=2, format="f")),
     ", P", .(ifelse(res$pval<.001, "<0.001",
                     paste0("=",formatC(res$pval, digits=2, format="f")))))))

```







```{r}
weights(res)

```


```{r}
funnel(res)

```

```{r}
names(data)
```




```{r}
data <- read.csv("data_final_suite.csv",sep=";",fileEncoding = "Latin1", check.names = F)
data


```



```{r}
##   TE : Treatment effect/Effect size = ln(RR/OR/HR)
##   seTE : Standard error of TE= OR Intervalle confidence/3.92=Upper-Lower/3.92



```


```{r}
data <- read.csv("data_final_suite.csv",sep=";",fileEncoding = "Latin1", check.names = F)
data

```
```{r}

data$RR<-gsub(",",".",data$RR)
data$TE<-gsub(",",".",data$TE)
data$seTE<-gsub(",",".",data$seTE)


data$RR<-as.numeric(as.character(data$RR))
data$TE<-as.numeric(as.character(data$TE))
data$seTE<-as.numeric(as.character(data$seTE))

data
```

```{r}


madata <- metagen(TE = TE,
            seTE = seTE,
            data = data,
            studlab = paste(Auteurs),
            comb.fixed = TRUE,
            comb.random = TRUE,
            method.tau = "DL",
            hakn = FALSE,
            prediction = TRUE,
            sm = "RR")

```

```{r}


forest(madata)



```


```{r}

funnel(madata, xlab = "Risk Ratio")


```




```{r}

names(data)


```

```{r}

# We will try to visualize the results of subgroup analyses based on 'MgSO4_regimen',
# 'Control', 'age nouveau né' Subgroup analysis based on 'MgSO4_regimen'
madata_rob <- metagen(TE = TE, seTE = seTE, data = data, studlab = paste(Auteurs), 
    comb.fixed = TRUE, comb.random = TRUE, method.tau = "DL", hakn = FALSE, prediction = TRUE, 
    sm = "RR", byvar = MgSO4_regimen)
ROB <- update(madata_rob, byvar = MgSO4_regimen, bylab = "Dose")


## Subgroup analysis based on 'Control'
madata_cont <- metagen(TE = TE, seTE = seTE, data = data, studlab = paste(Auteurs), 
    comb.fixed = TRUE, comb.random = TRUE, method.tau = "DL", hakn = FALSE, prediction = TRUE, 
    sm = "RR", byvar = Design)
control <- update(madata_cont, byvar = Design, bylab = "Design")

## Subgroup analysis based on 'age nouveau né'
madata_pop <- metagen(TE = TE, seTE = seTE, data = data, studlab = paste(Auteurs), 
    comb.fixed = TRUE, comb.random = TRUE, method.tau = "DL", hakn = FALSE, prediction = TRUE, 
    sm = "RR", byvar = age_nouveau_né)
population <- update(madata_pop, byvar = age_nouveau_né, bylab = "age nouveau né")



# Combining and visualizing the subgroup analyses
madata_subgroup <- metabind(ROB, control, population)
forest(madata_subgroup, rightcols = c("effect", "ci", "I2"))



```



```{r}



data |> 
  kbl(booktabs=TRUE,
      digits=2,
      format.args = list(decimal.mark="."),
      linesep = "" ,
      escape = FALSE) |> 
  kable_styling(latex_options=c("HOLD_position","scale_down"), bootstrap_options = c("condensed"), position="center") |>
  column_spec(1, width="4cm") |> 
  row_spec(0, bold = T)

```


```{r}
View(data_rob2)

```




```{r}

data_rob_2 <- read.csv("data_rob_2.csv",sep=";",fileEncoding = "Latin1", check.names = F)
data_rob_2

```



```{r}

data_rob_2$Weight<-gsub(",",".",data_rob_2$Weight)



data_rob_2$Weight<-as.numeric(as.character(data_rob_2$Weight))


data_rob_2
```


```{r}
# To print the summary of RoB assessments
rob_summary(data_rob_2, tool = "ROB2", weighted = FALSE, overall = TRUE)

```


```{r}

# To print the item-specific results of RoB assessments
rob_traffic_light(data_rob2, tool = "ROB2", psize = 8)
```

